id: I38E19E2E
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-ab38
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 09:41:03.726173+00:00
last_modified: 2023-09-26 09:41:03.726179+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC322
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC322
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་རྣམ་པར་བཤད་པ་ཐེག་ཆེན་ཆོས་ཀྱི་རྒྱ་མཚོ་ཟབ་རྒྱས་མཐའ་ཡས་པའི་སྙིང་པོ་ཞེས་བྱ་བ་བཞུགས་སོ།
  languages:
  - bo
  author: དཔའ་བོ ༠༢་གཙུག་ལག་འཕྲེང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.9975610391173153
  ocr_word_median_confidence_index: 1.0
bases:
  I2PD18627:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18627
      total_pages: 690
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18627.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9975610391173153
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
